apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
data:
  host: {{ awx_postgres_host | b64encode }}
  port: {{ awx_postgres_port | b64encode }}
  database: {{ awx_postgres_database | b64encode }}
  username: {{ awx_postgres_username | b64encode }}
  password: {{ awx_postgres_password | b64encode }}
  type: {{ awx_postgres_type | b64encode }}
